### ISSUE TITLE
Bayesian Advanced Setting

### ISSUE THREAD

**Issue by khollenbeck** [matgbar/IBI_VizEdit#25]
Program shut down (x'ed out if you will) when I clicked the Bayesian GP in advanced settings during editing

**Comment by matgbar** [comment]
Need more details. Was there a warning displayed in the R console, which computer were you working on? Is there anything else you can tell me about the issue (any screenshots even)?

**Comment by khollenbeck** [comment]
It just closed, the application was no longer open on the computer. I did not even have to shut down the application. I did not see a warning display in the R console-- I wish I could be more helpful. 
I was on the back computer (2 screens). Trevor and I have switched to the other room computer & I can try to go through the process and see if it happens again. 
-Kara 
    On Tuesday, February 20, 2018, 2:04:52 PM EST, matgbar <notifications@github.com> wrote:  
 
 
Need more details. Was there a warning displayed in the R console, which computer were you working on? Is there anything else you can tell me about the issue (any screenshots even)?

**Comment by khollenbeck** [comment]
Just trying to keep you updated-- maybe its me. 
    On Tuesday, February 20, 2018, 2:20:57 PM EST, Kara Hollenbeck <hollenbeck.kara@yahoo.com> wrote:  
 
  It just closed, the application was no longer open on the computer. I did not even have to shut down the application. I did not see a warning display in the R console-- I wish I could be more helpful. 
I was on the back computer (2 screens). Trevor and I have switched to the other room computer & I can try to go through the process and see if it happens again. 
-Kara 
    On Tuesday, February 20, 2018, 2:04:52 PM EST, matgbar <notifications@github.com> wrote:  
 
 
Need more details. Was there a warning displayed in the R console, which computer were you working on? Is there anything else you can tell me about the issue (any screenshots even)?

**Comment by khollenbeck** [comment]
```
Warning in max(temp.points$PPG) :
  no non-missing arguments to max; returning -Inf
Warning in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/khollenb/Documents\IBI_VizEdit_stan\GP_main.stan": The system cannot find the path specified
Warning in file(fname, "rt") :
  cannot open file 'C:\Users\khollenb\Documents\IBI_VizEdit_stan\GP_main.stan': No such file or directory
Error in file(fname, "rt") : cannot open the connection
Warning: Error in get_model_strcode: cannot open model file "C:\Users\khollenb\Documents\IBI_VizEdit_stan\GP_main.stan"
Stack trace (innermost first):
    69: get_model_strcode
    68: stanc
    67: stan_model
    66: stan
    65: observeEventHandler [C:/Users/khollenb/AppData/Local/Temp/Temp3_IBI_VizEdit-master.zip/IBI_VizEdit-master/VizEdit_v1_0_0.R#1672]
     1: runApp
ERROR: [on_request_read] connection reset by peer
```
Error message when I tried Bayesian again.

**Comment by matgbar** [comment]
`Warning: Error in get_model_strcode: cannot open model file "C:\Users\khollenb\Documents\IBI_VizEdit_stan\GP_main.stan"` 

That is exactly what I needed. You need to save this folder (available in the repository) exactly as it is named in your Documents folder. You will likely need to do this the first time you use any computer in the lab for editing.
