### ISSUE TITLE
Adjusting zoom from 5 to 1 

### ISSUE THREAD

**Issue by khollenbeck** [matgbar/IBI_VizEdit#27]
File 007_T2 
Severe lag zooming from Zoom 5 to Zoom 1 and back. Also, there just simply seems to be a slight issue with zoom in general. When you go from 5 to 1 repeatedly it continues zooming in-- appears that the peaks flatten out. 

At a zoom factor of 1 it was easy to see the variation in peak height and this screen shot shows what it is like at zoom factor of 5 (after going between zoom factor of 5 & 1 multiple times). There used to be a peak. 

![capture](https://user-images.githubusercontent.com/36546686/36562594-775319ee-17e5-11e8-9033-30ba81e3f286.PNG)

``` 

Listening on http://127.0.0.1:6696
Warning in max(temp.points$PPG) :
  no non-missing arguments to max; returning -Inf

```

**Comment by matgbar** [comment]
What screen are you showing here? Is this the advanced editing panel or is this the basic editing panel?

**Comment by matgbar** [comment]
Also which file was this?

**Comment by matgbar** [comment]
So I have adjusted the zoom. It no longer adjusts the amplitude of the raw signal. It does allow you to manually set the y axis, which will have to be adjusted using a slightly different strategy for certain edits.
