### ISSUE TITLE
"Fatal Error"

### ISSUE THREAD

**Issue by jkaye01** [matgbar/IBI_VizEdit#28]
was working on 002 T1 and R gave me a message that said "R Session Aborted. R encountered a fatal error. This session was terminated." I was almost done with the file and it shut down. I have a picture of it on my phone if you want to see the picture, I just don't know how to take screenshots on desktops.

**Comment by matgbar** [comment]
Go ahead and email me the screenshot. What did you do when it crashed?

**Comment by matgbar** [comment]
I am closing this issue for now as I cannot determine the underlying cause of the Session Abort. If it happens again, be sure to let me know
