### ISSUE TITLE
Saving Issue #2

### ISSUE THREAD

**Issue by TrevorAngert** [matgbar/IBI_VizEdit#30]
Hey Matt,
     I have now 'completed about 4 files' yet something is going wrong with the saving of said files. Every time I have completed a file and attempt to save, the program closes down, but does not completely end. In RStudio I am able to _resume app_ but when I do this, nothing in your application actually works, although it does let me interact with it. Attached is a picture of RStudio and I highlighted what seemed to change once the program 'crashed'. Additionally, I am still having some issues with file structure in order to utilize the advanced Bayesian function. I would appreciate if we could briefly sit down soon and hash out these issues, as they are seemingly something that I am doing incorrectly, and have no idea how to fix. I planned to finish about 3 files today alone, and likely would have been able to do more had these issues been there. If we could meet soon, it would help alleviate a lot of stress. 
 
![saving issue](https://user-images.githubusercontent.com/36676242/36754940-8c3efa16-1bd8-11e8-929b-43dfbeb5c95a.PNG)

**Comment by TrevorAngert** [comment]
I forgot to mention that I have had this issue for 001_T3, 002_T1, 002_T3, and 003_T1.

**Comment by matgbar** [comment]
So this is a super simple fix... And it is dumb that I left in there but the `browser()` function allows me to actively move through the code when I am debugging a function. In this case I should have added a `#` to the front of that line and the program would have worked as expected. You could also hit the Continue button that appears between the program and the Console in the RStudio window. 

In either case I will fix it tonight and post an updated program to the repository.

**Comment by matgbar** [comment]
Also tied to explanation here: Issue #31
