### ISSUE TITLE
HR Editing Panel Briefly Unavailable

### ISSUE THREAD

**Issue by dontgoratingmyheart** [matgbar/IBI_VizEdit#32]
Was unable to take a picture because restarting program seems to have corrected the issue.  However, to the best of my descriptive abilities, after processing the HR file and going to basic editing no file appeared.  I could see the updated "IBI Restore" button to the left along with some other unfamiliar features, but no PPG or IBI on the righthand side.

Update: happened again and got a pic: 
![ibi err](https://user-images.githubusercontent.com/36671027/36856443-060ac098-1d44-11e8-9b39-5e611f147e71.png)

**Comment by matgbar** [comment]
This looks highly similar to other issue you reported though the debugging is in a separate area of the program. 

See explanation here Issue #31
