### ISSUE TITLE
Tried to divide by .5 (007_T2)

### ISSUE THREAD

**Issue by ghaeuber** [matgbar/IBI_VizEdit#34]
I tried to divide a point by .5 and it erased the PPG data. I then tried to use the restore feature and it shut down the program.

``
![004_t3 issue capture](https://user-images.githubusercontent.com/36414298/36990645-5e5c2462-2073-11e8-994b-f7592e427bae.PNG)

``

**Comment by matgbar** [comment]
I'll work on adding a pop-up warning to prevent the crashing of the program.

That being said editors can only divide by integers. 

-Matt

**Comment by dontgoratingmyheart** [comment]
I also had this happen to me and got the error message, but I was also only dividing by an integer so I'm not sure what the problem was.

**Comment by matgbar** [comment]
@dontgoratingmyheart did the same warning appear (specifically referencing line #1368)?

**Comment by dontgoratingmyheart** [comment]
The "Error in [<-..." warning did not appear but everything below it did.

**Comment by dontgoratingmyheart** [comment]
![image](https://user-images.githubusercontent.com/36671027/37049740-d83989e2-213f-11e8-8da6-ca09c5707597.png)
 This happened the first time, and then it just happened again with this one:
![image](https://user-images.githubusercontent.com/36671027/37049833-2e82f036-2140-11e8-8138-f6553a229d79.png)

**Comment by matgbar** [comment]
Okay. These look to be unrelated. The issue is occurring at different lines of code under different circumstances.

**Comment by dontgoratingmyheart** [comment]
If it helps, in my cases the program was taking a while to select points
and turn them green for editing/sometimes the click-n-drag box would remain
even after I selected a different area.  I think these things in
conjunction may have been propogating incorrect or impossible edits in
other parts of the file, causing it to shut down

**Comment by matgbar** [comment]
Which computer were you on?

**Comment by dontgoratingmyheart** [comment]
The one with dual monitors all the way in the back room
