### ISSUE TITLE
App Non-responsive After Bayes

### ISSUE THREAD

**Issue by TrevorAngert** [matgbar/IBI_VizEdit#35]
**File Name**: 009_T3
**Issue**: After attempting to use the Bayes function, the program became non-responsive. It will allow me to switch between panels and highlight sections of the waveform, but nothing else. I am unsure if this section of code was related to this issue, but I will attach it anyways. Sebastian had the exact same issue occur to him as well (both of us are using the most up-to-date version of the application).
**Code**:
```
Listening on http://127.0.0.1:4970
Warning: Removed 125 rows containing missing values (geom_path).
Warning: Removed 13 rows containing missing values (geom_path).
Warning: Removed 13 rows containing missing values (geom_path).
Loading required namespace: rstudioapi
Warning: Removed 13 rows containing missing values (geom_path).
Warning: Removed 3176 rows containing missing values (geom_path).
Warning: Error in round: non-numeric argument to mathematical function
Stack trace (innermost first):
    85: renderPrint [C:/Users/tangert/Documents/IBI VizEdit/IBI_VizEdit-master/VizEdit_v1_1_0.R#1342]
    84: func
    83: eval
    82: eval
    81: withVisible
    80: evalVis
    79: utils::capture.output
    78: paste
    77: origRenderFunc
    76: output$hover_info2
     1: runApp
```

**Comment by TrevorAngert** [comment]
The program eventually became responsive again, after about 5 minutes

**Comment by matgbar** [comment]
Okay. I think there is a chance that this may have been the first time you ran the Bayesian imputation on that particular computer? If so that 5 minutes of dead air was probably the program compiling the C++ code for the Bayesian model.
