### ISSUE TITLE
App closed when attempting to add a point 

### ISSUE THREAD

**Issue by khollenbeck** [matgbar/IBI_VizEdit#36]
File 013_T3
```
Warning in max(temp.points$PPG) :
  no non-missing arguments to max; returning -Inf
Warning: Error in data.frame: arguments imply differing number of rows: 1304, 0
Stack trace (innermost first):
    66: data.frame
    65: observeEventHandler [C:/Users/khollenb/Downloads/IBI_VizEdit-master (1)/IBI_VizEdit-master/VizEdit_v1_1_0.R#1408]
     1: runApp
ERROR: [on_request_read] connection reset by peer
```

Had just compete a Bayesian GP, might be related to Trevor's issues.

**Comment by matgbar** [comment]
I just had something similar happen on a different file. I suspect the basic cause is the same though. I'll try to get this taken care of ASAP.

**Comment by matgbar** [comment]
This issue along with #37 should both be fixed at this stage. If something like this were to occur in the future, you should get a warning dialog instead of having the program crash.
