### ISSUE TITLE
Loooooong Bayesian Run Time

### ISSUE THREAD

**Issue by dontgoratingmyheart** [matgbar/IBI_VizEdit#39]
Process took 57.45 minutes to complete, after which point it experienced the same nonresponsive problem noted earlier by Trevor but did not correct itself naturally.

[004T1child57507_59331.txt](https://github.com/matgbar/IBI_VizEdit/files/1794056/004T1child57507_59331.txt)

**Comment by matgbar** [comment]
As of right now, an 18 second window for imputation is just too long for the program to handle. In this output I can see that the model struggled mightily to come up with reasonable estimates. Right now, based on my pilot testing over the last couple of days, the current program can really only reasonably estimate about 8-10 seconds max (with reasonable quality data surrounding the imputation window).

**Comment by matgbar** [comment]
[siglap1GP_only86559_88566.txt](https://github.com/matgbar/IBI_VizEdit/files/1795175/siglap1GP_only86559_88566.txt)

As a side note it takes my come computer with a much faster processor about 30 minutes to push through 20 seconds of messy data imputation.
