### ISSUE TITLE
Issue with the Combine Feature on 009_T1 

### ISSUE THREAD

**Issue by sebastianlangan1** [matgbar/IBI_VizEdit#45]
![ibi vizedit 1_2 bug 1](https://user-images.githubusercontent.com/34819697/37527029-5e8b6334-2907-11e8-865a-b5e4ea58dd7d.PNG)

File: 009_T1
Issue: Attempted to combine three different points about 5% of the way into the file. Then, they went completely off the y-axis (even setting it to 5 would not allow me to see the combined points). Also, attempting to scroll to the left or right to or enlarging the viewing frame did not allow me to view surrounding points afterwards.

**Comment by matgbar** [comment]
To start this signal is essentially noise at this location. It is hard to see a reasonable pattern for the pulsatile waveform. 

That being said, the y-axis appears to be manually scaled here. If that is the case and the values for your IBIs fall outside the local y-axis limits then you are likely to see "broken" sections of the IBI line graph.
