### ISSUE TITLE
Output Folder not Being Produced after Saving 009_T2

### ISSUE THREAD

**Issue by sebastianlangan1** [matgbar/IBI_VizEdit#46]
![ibi vizedit 1_2 bug 2 march 16th 2018](https://user-images.githubusercontent.com/34819697/37533718-08fc11b8-2919-11e8-9b67-d951e383f0b0.PNG)

File: 009_T2
Issue: When I try to save the file after spending an inordinate amount of time editing it, the Output Folder is not produced. Also, this is the error message shown.

**Comment by matgbar** [comment]
This is an old post, but I just want to make sure I am keeping a record of all issues and their resolutions. 

See the discussion here Issue #31 

The `browser()` function is a useful tool for debugging and something that I try to "turn off" when I push updates back to the repository. You can either type `c` in the console and hit enter or hit the continue button displayed in the bar above the console if this happens in the future. 

Also let me know when this happens so I can comment out the offending `browser()` function. 

-Matt
