### ISSUE TITLE
Large amount of glitching with the program

### ISSUE THREAD

**Issue by alyssagold** [matgbar/IBI_VizEdit#47]
There is a lot of freezing and glitching with the program. It is causing me to take a while with the file. I accidentally exited out of VizEdit before I could get the coding for it. However, after selecting the points to edit, the program was flashing which made it take a very long time to edit.

**Comment by matgbar** [comment]
"Glitching" is not a very descriptive explanation. What it sounds like is happening is that you are selecting points and it takes a while for the program to recognize the points you have selected. How large of a window are you using to view the heart rate data? The more data you include in your "active" editing window, the longer it will take the program to make adjustments to the plot area based on your selections.

**Comment by alyssagold** [comment]
Hi Matt,
     I'm not using much of a window to view the points, but I will look at
that next time. Thank you!
