### ISSUE TITLE
PPG signal not displaying properly

### ISSUE THREAD

**Issue by sebastianlangan1** [matgbar/IBI_VizEdit#48]
![bad science](https://user-images.githubusercontent.com/34819697/38269529-cc44d9a0-374e-11e8-90e4-e57aedb65f02.PNG)
Hi,

       I've been having an issue with 020_T2 in that the PPG displays as a tiny percentage of its correct amplitude. I would rather not irresponsibly edit this file without the PPG. What is up?

**Comment by matgbar** [comment]
Based on our discussions offline, this was an issue that had to do with misspecifying the column values for the PPG signal. The signal you sent is the result of the program importing a vector that was essentially just noise and then the algorithm identifying peaks wherever it could according to its own internal rules. 

So this specific issue should be resolved at this stage.
