### ISSUE TITLE
Program Closes After attempting to load file

### ISSUE THREAD

**Issue by dontgoratingmyheart** [matgbar/IBI_VizEdit#49]
After inputting all files and information, attempting to load for processing leads to this:

![image](https://user-images.githubusercontent.com/36671027/38564558-6027e00a-3cad-11e8-8fe6-aa034ac395c6.png)

**Comment by matgbar** [comment]
I am going to close this issue as it is likely related to either 1) not having the timing information in the file or 2) not having the correct header/column information specified in the data entry portal. If I am wrong about that it being one of those two issues, please let me know. 

-Matt
