### ISSUE TITLE
"Original Edits" in Case Processing Summary

### ISSUE THREAD

**Issue by kylebwilson** [matgbar/IBI_VizEdit#56]
In the Case Processing Summary File there are a bunch of pages at the end listing "original" edits that aren't actually edits which makes it difficult to see all the real edits that have been made.

![014_child kw_t2 _cases processing summary - compatibility mode - word 7_19_2018 1_23_56 pm](https://user-images.githubusercontent.com/40668960/42959527-248850ea-8b57-11e8-87b7-c314e61a6b0e.png)

**Comment by matgbar** [comment]
Fixed - this was a bud in the selection code. Using an "OR" operator when I needed an "AND" operator.

**Comment by matgbar** [comment]
To be clear this is fixed as of v1.2.3 (just finished putting it up on GitHub today.
